home/urls.py
from django.urls import path

from .views import home, like_link_post, delete_link_post

app_name = 'home'

urlpatterns = [
    path('like/', like_link_post, name='like_link_post'),
    path('delete/', delete_link_post, name='delete_link_post'),
    path('', home, name='homepage'),
]

like_machine_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
]

home/models.py
from django.db import models
from django.core.validators import MinValueValidator
from django.contrib.auth import get_user_model


class LinkPost(models.Model):
    author = models.ForeignKey(
        get_user_model(),
        related_name='links',
        on_delete=models.CASCADE
    )
    title = models.CharField(max_length=300)
    link = models.URLField()
    created = models.DateTimeField(auto_now_add=True)
    liked_by = models.ManyToManyField(get_user_model(), related_name='likes')
    total_likes = models.PositiveIntegerField(
        default=0, validators=[MinValueValidator(0)]
    )

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'{self.title}'

users/models.py
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    pass

home/forms.py
from django import forms

from .models import LinkPost


class LinkPostForm(forms.ModelForm):
    class Meta:
        model = LinkPost
        fields = ('title', 'link')

home/views.py
from django.shortcuts import render
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.db.models import DateField
from django.db.models.functions import Trunc

from common.decorators import ajax_required

from .models import LinkPost
from .forms import LinkPostForm


def home(request):
    """
    Homepage view loads all the LinkPosts
    and a form to create LinkPost
    """

    # linkposts are ordered by day then by total likes they have
    links = LinkPost.objects.annotate(
        day_created=Trunc('created', 'day', output_field=DateField()))\
        .order_by('-day_created', '-total_likes')

    # create a linkpost
    if request.method == 'POST':
        link_post_form = LinkPostForm(request.POST)
        if link_post_form.is_valid():
            link_post_obj = link_post_form.save(commit=False)
            link_post_obj.author = request.user
            link_post_obj.save()

    # linkpost form
    link_post_form = LinkPostForm()

    # get posts already liked by logged-in user
    user_likes = None
    if request.user.is_authenticated:
        user_likes = LinkPost.objects.filter(liked_by=request.user)

    return render(request, 'home/homepage.html', {
        'links': links,
        'link_post_form': link_post_form,
        'user_likes': user_likes,
    })


@ajax_required
@require_POST
@login_required
def like_link_post(request):
    """
    Ajax view to like/unlike a linkpost
    gets linkpost id and action from request data
    """
    link_post_id = request.POST.get('id')
    action = request.POST.get('action')
    if link_post_id and action:
        try:
            link_post = LinkPost.objects.get(id=link_post_id)
            if action == 'like':
                # Prevent multiple like requests
                if not LinkPost.objects.filter(liked_by=request.user):
                    link_post.total_likes += 1
                    link_post.liked_by.add(request.user)
            else:
                # Prevent multiple unlike requests
                if LinkPost.objects.filter(liked_by=request.user):
                    link_post.total_likes -= 1
                    link_post.liked_by.remove(request.user)
            link_post.save()

            return JsonResponse({
                'status': 'ok',
                'link_post_id': link_post_id
            })

        except LinkPost.DoesNotExist:
            return JsonResponse({'status': 'ko'})

    return JsonResponse({'status': 'ko'})


@ajax_required
@require_POST
@login_required
def delete_link_post(request):
    """
    Ajax view to delete a linkpost
    """
    link_post_id = request.POST.get('id')
    action = request.POST.get('action')
    if link_post_id and action:
        try:
            link_post = LinkPost.objects.get(id=link_post_id)
            if action == 'delete':
                # Only author should be able to delete its post
                if link_post.author == request.user:
                    link_post.delete()

            return JsonResponse({
                'status': 'ok',
                'link_post_id': link_post_id
            })

        except LinkPost.DoesNotExist:
            return JsonResponse({'status': 'ko'})

    return JsonResponse({'status': 'ko'})

users/views.py
from django.shortcuts import render

# Create your views here.

templates/_base.html
{% load static %} {% load socialaccount %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- CSS only -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous"
    />
    <script
      src="https://code.jquery.com/jquery-3.6.0.min.js"
      integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
      crossorigin="anonymous"
    ></script>
    <title>{% block title %}Like Machine{% endblock title %}</title>
  </head>
  <body>
    <div class="container-fluid">
      <div class="row">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <div class="container-fluid">
            <a class="navbar-brand" href="#">Like Machine</a>
            <button
              class="navbar-toggler"
              type="button"
              data-bs-toggle="collapse"
              data-bs-target="#navbarNavDropdown"
              aria-controls="navbarNavDropdown"
              aria-expanded="false"
              aria-label="Toggle navigation"
            >
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                {% if user.is_authenticated %}
                <li class="nav-item">Hi {{ user.username }}!</li>
                {% endif %}
              </ul>
              {% if user.is_authenticated %}
              <form action="{% url 'account_logout' %}" method="post">
                {% csrf_token %}
                <button type="submit" class="btn btn-outline-danger">
                  Logout
                </button>
              </form>
              {% else %}
              <a
                class="btn btn-outline-secondary"
                href="{% provider_login_url 'github' %}"
                ><img
                  style="width: 20px"
                  src="{% static 'images/GitHub-Mark-64px.png' %}"
                />GitHub Login</a
              >
              {% endif %}
            </div>
          </div>
        </nav>
      </div>
      <div class="content">{% block content %} {% endblock content %}</div>
    </div>
    <!-- JS -->
    <!-- JavaScript Bundle with Popper -->
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
      crossorigin="anonymous"
    ></script>

    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script>
      var csrftoken = Cookies.get('csrftoken');
      function csrfSafeMethod(method) {
        // these methods don't need csrf protection
        return /^(GET | HEAD | OPTIONS | TRACE)$/.test(method);
      }
      $.ajaxSetup({
        beforeSend: function (xhr, settings) {
          if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader('X-CSRFToken', csrftoken);
          }
        },
      });
    </script>
    {% block scripts %} {% endblock scripts %}
  </body>
</html>

templates/home/delete_button.html
{% if link.author == user %}
<button
  href="#"
  class="delete-button btn btn-outline-danger"
  id="{{ link.id }}"
  data-id="{{ link.id }}"
  data-action="delete"
>
  Delete Post
</button>
{% endif %}

<script>
  $('button.delete-button').click(function (e) {
    e.stopImmediatePropagation();
    e.preventDefault();
    $.post(
      '{% url "home:delete_link_post" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action'),
      },
      function (data) {
        if (data['status'] == 'ok') {
          var link_post_id = data['link_post_id'];
          var link_post_id_selector = '#card-' + link_post_id;
          // update DOM
          $(link_post_id_selector).remove();
        }
      }
    );
  });
</script>

templates/home/homepage.html
{% extends '_base.html' %} {% block content %}
<div class="row">
  <div class="col-8">
    {% for link in links %}
    <div class="card" id="card-{{ link.id }}">
      <div class="card-body">
        <h5 class="card-title">{{ link.title }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <a href="{{ link.link }}" target="_blank" rel="noopener noreferrer"
            >{{ link.link }}</a
          >
        </h6>
        <br />
        <figcaption class="blockquote-footer">
          Created on {{ link.created }} by {{ link.author }}
        </figcaption>
        <!-- include ajax button -->
        {% include 'home/like_button.html' %}
        {% include 'home/delete_button.html' %}
        <p>
          Total likes:
          <span class="likes-count" id="likes-count-{{ link.id }}"
            >{{ link.total_likes }}</span
          >
        </p>
      </div>
    </div>
    {% endfor %}
  </div>
  <!-- include post link form -->
  {% include 'home/link_post_form.html' %}
</div>
{% endblock content %}

templates/home/like_button.html
{% if user.is_authenticated %}
<button
  href="#"
  class="like-button btn btn-outline-{% if link in user_likes %}danger{% else %}success{% endif %}"
  id="{{ link.id }}"
  data-id="{{ link.id }}"
  data-action="{% if link in user_likes %}un{% endif %}like"
>
  {% if link in user_likes %} Unlike {% else %} Like {% endif %}
</button>
{% endif %}

<script>
  $('button.like-button').click(function (e) {
    e.stopImmediatePropagation();
    e.preventDefault();
    $.post(
      '{% url "home:like_link_post" %}',
      {
        id: $(this).data('id'),
        action: $(this).data('action'),
      },
      function (data) {
        if (data['status'] == 'ok') {
          var link_post_id = data['link_post_id'];
          var link_post_id_selector = '#' + link_post_id;
          var previous_action = $(link_post_id_selector).data('action');
          // update DOM
          $(link_post_id_selector).data(
            'action',
            previous_action == 'like' ? 'unlike' : 'like'
          );
          $(link_post_id_selector).text(
            previous_action == 'like' ? 'Unlike' : 'Like'
          );
          if(previous_action == 'like'){
            $(link_post_id_selector).removeClass('btn-outline-primary')
            $(link_post_id_selector).addClass('btn-outline-danger')
          } else {
            $(link_post_id_selector).addClass('btn-outline-primary')
            $(link_post_id_selector).removeClass('btn-outline-danger')
          }

          // change likes count
          var previous_likes_count = parseInt(
            $('#likes-count-' + link_post_id).text()
          );
          $('#likes-count-' + link_post_id).text(
            previous_action == 'like'
              ? previous_likes_count + 1
              : previous_likes_count - 1
          );
        }
      }
    );
  });
</script>

templates/home/link_post_form.html
{% load crispy_forms_tags %}
<div class="col-3">
  <h4>Create a new link-post</h4>
  {% if user.is_authenticated %}
  <form method="post">
    {{ link_post_form | crispy }} {% csrf_token %}
    <button class="btn btn-primary" type="submit">
      Create a new link-post
    </button>
  </form>
  {% else %}
  <h5>Please log-in using link in header</h5>
  {% endif %}
</div>